config/routes.rb
GmailTest::Application.routes.draw do

  resources :users do
    member do
      get 'gmail'
      get 'new_gmail_session'
      get 'create_gmail_session'
      post 'destroy_gmail_session'
    end
  end

  root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :inbox_size, :oauth_token, :oauth_secret

  def logged_in?
    oauth_token && oauth_secret
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
require 'gmail_xoauth'
require 'nokogiri'

class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, :notice => "Successfully created user."
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end

  def new_gmail_session
    consumer = get_consumer
    @user = User.find(params[:id])
    next_url = "http://localhost:3000/users/#{params[:id]}/create_gmail_session"
    scope = "https://mail.google.com/ https://www.google.com/m8/feeds/"
    puts "scope: #{scope}"
    request_token = consumer.get_request_token( {:oauth_callback => next_url}, {:scope => scope} )
    session[:oauth_secret] = request_token.secret
    redirect_to request_token.authorize_url
  end

  def create_gmail_session
    @user = User.find(params[:id])
    request_token = OAuth::RequestToken.new(get_consumer, params[:oauth_token], session[:oauth_secret])
    session[:oauth_secret] = nil
    access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    @user.oauth_token  =  access_token.token
    @user.oauth_secret =  access_token.secret
    xml = Nokogiri.XML(access_token.get("https://www.google.com/m8/feeds/contacts/default/full/").body)
    @user.email = xml.at_css('id').content
    puts "#{@user.email}"
    @user.save
    redirect_to :action => :gmail
  end

  def destroy_gmail_session
    reset_session
    flash[:notice] = "You have been logged out"
    redirect_to :action => 'new'
  end

  def gmail
    @user = User.find(params[:id])
    gmail = GmailXoauth.new(@user.email, @user.oauth_token, @user.oauth_secret, "hobstr.com", "Ex46_y1b_oELupr5pSge9SNq")
    @user.inbox_size = gmail.inbox.count
    @user.save
    gmail.peek
    gmail.inbox.emails(:read, :after => Date.parse("2012-02-11")).each do |email|
      flash[:notice] = email.body
    end
    render :show
  end

private
 
  def get_consumer
    require 'oauth/consumer'
    consumer = OAuth::Consumer.new("hobstr.com", "Ex46_y1b_oELupr5pSge9SNq",
                                   {
                                     :site => "https://www.google.com/",
                                     :request_token_path => "/accounts/OAuthGetRequestToken",
                                     :access_token_path => "/accounts/OAuthGetAccessToken",
                                     :authorize_path=> "/accounts/OAuthAuthorizeToken"})                                                                       
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg.html_safe) }
        content_tag(:h2, options[:header_message].html_safe) + content_tag(:p, options[:message].html_safe) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render "form" %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Inbox Size</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.inbox_size %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "New User" %>

<%= render "form" %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Inbox Size:</strong>
  <%= @user.inbox_size %>
</p>

<%= link_to "Get gmails", new_gmail_session_user_path(@user) %> 


<br /><br /><br /><br /><br /><br /><br />
<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>